<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\{
    User,
    PersonalInfoField,
    MedicalHistoryField,
    Department,
    Course,
};
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Collection;

class UserSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $superAdmin = User::create([
            'username' => 'superadmin',
            'password' => Hash::make('superadmin'),
        ]);
        $superAdmin->assignRole('Super Admin');

        $admins = ['admin1', 'admin2', 'admin3'];
        foreach ($admins as $admin) {
            $user = User::create([
                'username' => $admin,
                'password' => Hash::make('admin'),
            ]);
            $user->assignRole('Admin');
        }

        $personalInfoFields = $this->fieldsByName(PersonalInfoField::class);
        $medicalHistoryFields = $this->fieldsByName(MedicalHistoryField::class);

        $students = ['student1', 'student2', 'student3'];
        foreach ($students as $student) {
            $studentId = $this->generateStudentId();

            $user = User::create([
                'username' => $studentId,
                'password' => Hash::make('student'),
            ]);
            $user->assignRole('Student');

            [$personalInfoAnswers, $medicalHistoryAnswers] = $this->generateStudentAnswers();

            $this->storeAnswers($user, 'personalInfos', 'personal_info_field_id', $personalInfoFields, $personalInfoAnswers);
            $this->storeAnswers($user, 'medicalHistories', 'medical_history_field_id', $medicalHistoryFields, $medicalHistoryAnswers);
        }
    }

    /**
     * Map field_name => field_id for the given model's currently seeded
     * fields, so answers below can be generated by name rather than by
     * fragile, migration-order-dependent ids.
     */
    private function fieldsByName(string $modelClass): Collection
    {
        return $modelClass::with('latestVersion')
            ->get()
            ->filter(fn ($field) => $field->latestVersion?->field_name !== null)
            ->mapWithKeys(fn ($field) => [$field->latestVersion->field_name => $field->id]);
    }

    /**
     * Create one EAV row per generated answer whose field name is present in
     * $fieldIds (unknown/renamed/removed fields, and any answer that came
     * back null, are skipped).
     */
    private function storeAnswers(User $user, string $relation, string $foreignKey, Collection $fieldIds, array $answers): void
    {
        foreach ($answers as $fieldName => $value) {
            if ($value === null || ! $fieldIds->has($fieldName)) {
                continue;
            }

            $user->{$relation}()->create([
                $foreignKey => $fieldIds[$fieldName],
                'value' => is_array($value) ? json_encode($value) : (string) $value,
            ]);
        }
    }

    private function generateStudentId(): string
    {
        $prefixes = ['0123', '0124', '0125', '0126'];
        $prefix = fake()->randomElement($prefixes);

        $lastUsername = User::where('username', 'like', $prefix . '%')
            ->orderByDesc('username')
            ->value('username');

        $lastSuffix = $lastUsername ? substr($lastUsername, 4) : null;
        $newSuffix = $lastSuffix ? str_pad((int) $lastSuffix + 1, 6, '0', STR_PAD_LEFT) : '000001';

        return $prefix . $newSuffix;
    }

    /**
     * Generates a matched pair of [personal_info, medical_history] answers,
     * keyed by field_name, following the same random-data logic as the old
     * generateStudentInfo() — extended with sensible generation for the
     * additional fields the old StudentInfo model didn't have.
     */
    private function generateStudentAnswers(): array
    {
        $lastName = fake()->lastName();

        $year = fake()->numberBetween(0, 16);
        if ($year <= 12) {
            $educationLevel = 'BASIC_ED';
            $department = null;
            $course = null;
            $section = 'Section-' . fake()->numberBetween(1, 10);
            if ($year === 0) {
                $yearLevel = 'Kindergarten';
            } else {
                $yearLevel = 'Grade ' . $year;
            }
        } else {
            switch ($year) {
                case 13:
                    $yearLevel = '1st Year';
                    $sectionCode = 1;
                    break;
                case 14:
                    $yearLevel = '2nd Year';
                    $sectionCode = 3;
                    break;
                case 15:
                    $yearLevel = '3rd Year';
                    $sectionCode = 5;
                    break;
                case 16:
                    $yearLevel = '4th Year';
                    $sectionCode = 7;
                    break;
            }
            $educationLevel = 'COLLEGE';
            $department = Department::inRandomOrder()->first();
            $course = $department
                ? Course::where('department_id', $department->id)->inRandomOrder()->first()
                : null;
            $section = ($department?->code ?? 'GEN') . (string) $sectionCode . fake()->randomElement(['A', 'B', 'C', 'D']);
        }

        $covidVaccinated = fake()->boolean();

        $personalInfo = [
            'First Name' => fake()->firstName(),
            'Last Name' => $lastName,
            'Middle Name' => fake()->lastName(),
            'Date of Birth' => fake()->date(),
            'Gender' => fake()->randomElement(['MALE', 'FEMALE']),
            'Religion' => fake()->randomElement(['Roman Catholic', 'Protestant', 'Islam', 'Other']),
            'Nationality' => 'Filipino',
            'Address' => fake()->address(),
            'Contact Number' => fake()->phoneNumber(),
            'Education Level' => $educationLevel,
            'Grade Level' => $educationLevel === 'BASIC_ED' ? $yearLevel : null,
            'Year Level' => $educationLevel === 'COLLEGE' ? $yearLevel : null,
            'Department' => $department?->code,
            'Course' => $course?->code,
            'Section' => $section,
            "Mother's Name" => fake()->firstName('female') . ' ' . $lastName,
            "Father's Name" => fake()->firstName('male') . ' ' . $lastName,
            "Guardian's Name" => fake()->firstName() . ' ' . $lastName,
            'Contact No. of Guardian' => fake()->phoneNumber(),
            'Contact Name' => fake()->name(),
            'Contact No.' => fake()->phoneNumber(),
        ];

        $medicalHistory = [
            'Any present illnesses?' => fake()->randomElement(['YES', 'NO']),
            'Any Physical injuries/serious illness within the last 5 years?' => fake()->randomElement(['YES', 'NO']),
            'Have you been hospitalized within the last 5 years?' => fake()->randomElement(['YES', 'NO']),
            'Cigarette smoking?' => fake()->randomElement(['YES', 'NO']),
            'Alcohol beverage use?' => fake()->randomElement(['YES', 'NO']),
            'Vaccinated for COVID-19?' => $covidVaccinated ? 'YES' : 'NO',
            'Vaccine Name' => $covidVaccinated ? 'Pfizer' : null,
            '1st Dose' => $covidVaccinated ? fake()->date() : null,
            '2nd Dose' => $covidVaccinated ? fake()->date() : null,
            '1st Booster' => $covidVaccinated && fake()->boolean() ? fake()->date() : null,
            '2nd Booster' => $covidVaccinated && fake()->boolean(30) ? fake()->date() : null,
            'Other Vaccines' => fake()->randomElements(
                ['Measles Containing Vaccine', 'Tetanus Diptheria', 'Human Papiloma Virus', 'Measles Rubella'],
                fake()->numberBetween(0, 2)
            ),
            'Illnesses' => fake()->randomElements(
                ['Allergy', 'Asthma', 'Hypertension', 'Diabetes', 'Heart Disorder', 'Tuberculosis or Seizure', 'Other'],
                fake()->numberBetween(0, 2)
            ),
            'Has any special medication:' => fake()->randomElement(['YES', 'NO']),
            'Requires Special care/precaution concerning health:' => fake()->randomElement(['YES', 'NO']),
            'Is allergic to any drug/food preparation:' => fake()->randomElement(['YES', 'NO']),
            'Have limitations or restrictions on certain activities:' => fake()->randomElement(['YES', 'NO']),
        ];

        return [$personalInfo, $medicalHistory];
        }
    }